/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/crawl-jobs/{crawl_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crawl Job */
        get: operations["get_crawl_job_api_v1_crawl_jobs__crawl_job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawl-jobs/{crawl_job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Crawl */
        post: operations["cancel_crawl_api_v1_crawl_jobs__crawl_job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Organizations */
        get: operations["list_organizations_api_v1_organizations_get"];
        put?: never;
        /** Create Organization */
        post: operations["create_organization_api_v1_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization */
        get: operations["get_organization_api_v1_organizations__organization_id__get"];
        /** Update Organization */
        put: operations["update_organization_api_v1_organizations__organization_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_v1_organizations__organization_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_api_v1_organizations__organization_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_api_v1_organizations__organization_id__members__user_id__patch"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        /** Update Project */
        put: operations["update_project_api_v1_projects__project_id__put"];
        post?: never;
        /** Archive Project */
        delete: operations["archive_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/websites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Websites */
        get: operations["list_websites_api_v1_projects__project_id__websites_get"];
        put?: never;
        /** Create Website */
        post: operations["create_website_api_v1_projects__project_id__websites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current User */
        get: operations["current_user_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{website_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Website */
        get: operations["get_website_api_v1_websites__website_id__get"];
        /** Update Website */
        put: operations["update_website_api_v1_websites__website_id__put"];
        post?: never;
        /** Archive Website */
        delete: operations["archive_website_api_v1_websites__website_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{website_id}/crawl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Crawl */
        post: operations["start_crawl_api_v1_websites__website_id__crawl_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{website_id}/crawl-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Crawl Jobs */
        get: operations["list_crawl_jobs_api_v1_websites__website_id__crawl_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{website_id}/crawl-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crawl Status */
        get: operations["get_crawl_status_api_v1_websites__website_id__crawl_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{website_id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Links */
        get: operations["list_links_api_v1_websites__website_id__links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{website_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pages */
        get: operations["list_pages_api_v1_websites__website_id__pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{website_id}/pages/{page_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page */
        get: operations["get_page_api_v1_websites__website_id__pages__page_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{website_id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Verification Info */
        get: operations["get_verification_info_api_v1_websites__website_id__verification_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/websites/{website_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Website */
        post: operations["verify_website_api_v1_websites__website_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiResponse[ContentPageDetail] */
        ApiResponse_ContentPageDetail_: {
            data: components["schemas"]["ContentPageDetail"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[ContentPageList] */
        ApiResponse_ContentPageList_: {
            data: components["schemas"]["ContentPageList"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[CrawlJobDetail] */
        ApiResponse_CrawlJobDetail_: {
            data: components["schemas"]["CrawlJobDetail"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[CrawlJobList] */
        ApiResponse_CrawlJobList_: {
            data: components["schemas"]["CrawlJobList"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[CrawlStatusSummary] */
        ApiResponse_CrawlStatusSummary_: {
            data: components["schemas"]["CrawlStatusSummary"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[OrganizationDetail] */
        ApiResponse_OrganizationDetail_: {
            data: components["schemas"]["OrganizationDetail"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[OrganizationList] */
        ApiResponse_OrganizationList_: {
            data: components["schemas"]["OrganizationList"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[OrganizationMemberDetail] */
        ApiResponse_OrganizationMemberDetail_: {
            data: components["schemas"]["OrganizationMemberDetail"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[OrganizationMemberList] */
        ApiResponse_OrganizationMemberList_: {
            data: components["schemas"]["OrganizationMemberList"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[PageLinkList] */
        ApiResponse_PageLinkList_: {
            data: components["schemas"]["PageLinkList"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[ProjectDetail] */
        ApiResponse_ProjectDetail_: {
            data: components["schemas"]["ProjectDetail"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[ProjectList] */
        ApiResponse_ProjectList_: {
            data: components["schemas"]["ProjectList"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[UserDetail] */
        ApiResponse_UserDetail_: {
            data: components["schemas"]["UserDetail"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[WebsiteDetail] */
        ApiResponse_WebsiteDetail_: {
            data: components["schemas"]["WebsiteDetail"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[WebsiteList] */
        ApiResponse_WebsiteList_: {
            data: components["schemas"]["WebsiteList"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[WebsiteVerificationDetail] */
        ApiResponse_WebsiteVerificationDetail_: {
            data: components["schemas"]["WebsiteVerificationDetail"] | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[dict[str, str]] */
        ApiResponse_dict_str__str__: {
            /** Data */
            data: {
                [key: string]: string;
            } | null;
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ContentPageDetail */
        ContentPageDetail: {
            /** Canonical Url */
            canonical_url: string | null;
            /** Cleaned Content */
            cleaned_content: string;
            /** Content Hash */
            content_hash: string;
            /** Content Status */
            content_status: string;
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Headings
             * @default []
             */
            headings: Record<string, never>[];
            /** Http Status */
            http_status: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Images
             * @default []
             */
            images: Record<string, never>[];
            /** Language */
            language: string;
            /** Last Crawled At */
            last_crawled_at: string | null;
            /** Meta Description */
            meta_description: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: Record<string, never>;
            /** Normalized Url */
            normalized_url: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Structured Content */
            structured_content: Record<string, never>;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string;
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
            /** Word Count */
            word_count: number;
        };
        /** ContentPageList */
        ContentPageList: {
            /** Items */
            items: components["schemas"]["ContentPageSummary"][];
        };
        /** ContentPageSummary */
        ContentPageSummary: {
            /** Canonical Url */
            canonical_url: string | null;
            /** Content Status */
            content_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Http Status */
            http_status: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Crawled At */
            last_crawled_at: string | null;
            /** Normalized Url */
            normalized_url: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
            /** Word Count */
            word_count: number;
        };
        /** CrawlConfiguration */
        CrawlConfiguration: {
            /**
             * Allowed Paths
             * @description Subpath prefixes to allow
             */
            allowed_paths?: string[];
            /**
             * Blocked Paths
             * @description Subpath prefixes to block
             */
            blocked_paths?: string[];
            /**
             * Crawl Delay
             * @description Politeness delay between fetches in seconds
             * @default 0.2
             */
            crawl_delay: number;
            /**
             * Include Subdomains
             * @description Include subdomains of verified host
             * @default false
             */
            include_subdomains: boolean;
            /**
             * Max Depth
             * @description Maximum crawl depth
             * @default 4
             */
            max_depth: number;
            /**
             * Max Pages
             * @description Maximum pages to crawl
             * @default 200
             */
            max_pages: number;
            /**
             * Respect Robots
             * @description Respect robots.txt directives
             * @default true
             */
            respect_robots: boolean;
            /**
             * User Agent
             * @description Custom crawler User-Agent
             * @default Antigravity-ContentAgent/1.0
             */
            user_agent: string;
        };
        /** CrawlJobCreate */
        CrawlJobCreate: {
            configuration?: components["schemas"]["CrawlConfiguration"];
        };
        /** CrawlJobDetail */
        CrawlJobDetail: {
            /** Completed At */
            completed_at: string | null;
            /** Configuration */
            configuration: Record<string, never>;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Count */
            error_count: number;
            /** Error Summary */
            error_summary: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Pages Crawled */
            pages_crawled: number;
            /** Pages Discovered */
            pages_discovered: number;
            /** Pages Failed */
            pages_failed: number;
            /** Pages Skipped */
            pages_skipped: number;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Requested By Id */
            requested_by_id: string | null;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
        };
        /** CrawlJobList */
        CrawlJobList: {
            /** Items */
            items: components["schemas"]["CrawlJobDetail"][];
        };
        /** CrawlStatusSummary */
        CrawlStatusSummary: {
            active_job?: components["schemas"]["CrawlJobDetail"] | null;
            last_job?: components["schemas"]["CrawlJobDetail"] | null;
            /**
             * Total Indexed Pages
             * @default 0
             */
            total_indexed_pages: number;
            /** Verification Status */
            verification_status: string;
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
        };
        /**
         * ErrorItem
         * @description Stable machine-readable error entry.
         */
        ErrorItem: {
            /** Code */
            code: string;
            /** Details */
            details?: Record<string, never>;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MembershipStatus
         * @enum {string}
         */
        MembershipStatus: "active" | "suspended";
        /** OrganizationCreate */
        OrganizationCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
        };
        /** OrganizationDetail */
        OrganizationDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Revision */
            revision: number;
            /** Slug */
            slug: string;
            status: components["schemas"]["MembershipStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OrganizationList */
        OrganizationList: {
            /** Items */
            items: components["schemas"]["OrganizationDetail"][];
        };
        /** OrganizationMemberCreate */
        OrganizationMemberCreate: {
            role: components["schemas"]["RoleCode"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** OrganizationMemberDetail */
        OrganizationMemberDetail: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            role: components["schemas"]["RoleCode"];
            /** Status */
            status: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** OrganizationMemberList */
        OrganizationMemberList: {
            /** Items */
            items: components["schemas"]["OrganizationMemberDetail"][];
        };
        /** OrganizationMemberUpdate */
        OrganizationMemberUpdate: {
            role: components["schemas"]["RoleCode"];
            /** Status */
            status: string;
        };
        /**
         * OrganizationStatus
         * @enum {string}
         */
        OrganizationStatus: "active" | "suspended" | "archived";
        /** OrganizationUpdate */
        OrganizationUpdate: {
            /** Name */
            name: string;
            /** Revision */
            revision: number;
            /** Slug */
            slug: string;
            status: components["schemas"]["OrganizationStatus"];
        };
        /** PageLinkDetail */
        PageLinkDetail: {
            /** Anchor Text */
            anchor_text: string;
            /**
             * Discovered At
             * Format: date-time
             */
            discovered_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Internal */
            is_internal: boolean;
            /** Nofollow */
            nofollow: boolean;
            /** Normalized Target Url */
            normalized_target_url: string;
            /** Rel */
            rel: string | null;
            /**
             * Source Page Id
             * Format: uuid
             */
            source_page_id: string;
            /** Sponsored */
            sponsored: boolean;
            /** Target Page Id */
            target_page_id: string | null;
            /** Target Url */
            target_url: string;
            /** Ugc */
            ugc: boolean;
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
        };
        /** PageLinkList */
        PageLinkList: {
            /** Items */
            items: components["schemas"]["PageLinkDetail"][];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Default Country */
            default_country?: string | null;
            /**
             * Default Locale
             * @default en
             */
            default_locale: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Slug */
            slug?: string | null;
        };
        /** ProjectDetail */
        ProjectDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Country */
            default_country: string | null;
            /** Default Locale */
            default_locale: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Revision */
            revision: number;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectList */
        ProjectList: {
            /** Items */
            items: components["schemas"]["ProjectDetail"][];
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "archived";
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Default Country */
            default_country?: string | null;
            /** Default Locale */
            default_locale: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** Revision */
            revision: number;
            /** Slug */
            slug: string;
            status: components["schemas"]["ProjectStatus"];
        };
        /**
         * ResponseMeta
         * @description Request metadata shared by success and failure responses.
         */
        ResponseMeta: {
            /** Has More */
            has_more?: boolean | null;
            /** Next Cursor */
            next_cursor?: string | null;
            /** Request Id */
            request_id: string;
        };
        /**
         * RoleCode
         * @enum {string}
         */
        RoleCode: "admin" | "seo_manager" | "content_manager" | "writer" | "editor" | "viewer";
        /** UserDetail */
        UserDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WebsiteCreate */
        WebsiteCreate: {
            /** Country */
            country?: string | null;
            /**
             * Locale
             * @default en
             */
            locale: string;
            /** Name */
            name: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** WebsiteDetail */
        WebsiteDetail: {
            /** Base Url */
            base_url: string;
            /** Country */
            country: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locale */
            locale: string;
            /** Name */
            name: string;
            /** Normalized Host */
            normalized_host: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Revision */
            revision: number;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Verification Status */
            verification_status: string;
        };
        /** WebsiteList */
        WebsiteList: {
            /** Items */
            items: components["schemas"]["WebsiteDetail"][];
        };
        /**
         * WebsiteStatus
         * @enum {string}
         */
        WebsiteStatus: "active" | "inactive" | "archived";
        /** WebsiteUpdate */
        WebsiteUpdate: {
            /** Country */
            country?: string | null;
            /** Locale */
            locale: string;
            /** Name */
            name: string;
            /** Revision */
            revision: number;
            status: components["schemas"]["WebsiteStatus"];
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** WebsiteVerificationDetail */
        WebsiteVerificationDetail: {
            /** File Snippet */
            file_snippet: string;
            /** Meta Tag Snippet */
            meta_tag_snippet: string;
            /** Verification Status */
            verification_status: string;
            /** Verification Token */
            verification_token: string;
            /** Verified At */
            verified_at: string | null;
            /**
             * Website Id
             * Format: uuid
             */
            website_id: string;
        };
        /** WebsiteVerificationRequest */
        WebsiteVerificationRequest: {
            /**
             * Method
             * @description Verification method: 'http_meta', 'http_header', or 'verification_file'
             * @default http_meta
             */
            method: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_crawl_job_api_v1_crawl_jobs__crawl_job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crawl_job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CrawlJobDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_crawl_api_v1_crawl_jobs__crawl_job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crawl_job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CrawlJobDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organizations_api_v1_organizations_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_OrganizationList_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_api_v1_organizations_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_OrganizationDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_api_v1_organizations__organization_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_OrganizationDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_organization_api_v1_organizations__organization_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_OrganizationDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_organizations__organization_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_OrganizationMemberList_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_v1_organizations__organization_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationMemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_OrganizationMemberDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_v1_organizations__organization_id__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationMemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_OrganizationMemberDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query: {
                organization_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectList_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_websites_api_v1_projects__project_id__websites_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_WebsiteList_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_website_api_v1_projects__project_id__websites_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebsiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_WebsiteDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_user_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UserDetail_"];
                };
            };
        };
    };
    get_website_api_v1_websites__website_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                website_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_WebsiteDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_website_api_v1_websites__website_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                website_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebsiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_WebsiteDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_website_api_v1_websites__website_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                website_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_WebsiteDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_crawl_api_v1_websites__website_id__crawl_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                website_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CrawlJobDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_crawl_jobs_api_v1_websites__website_id__crawl_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                website_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CrawlJobList_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawl_status_api_v1_websites__website_id__crawl_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                website_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CrawlStatusSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_links_api_v1_websites__website_id__links_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                website_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PageLinkList_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pages_api_v1_websites__website_id__pages_get: {
        parameters: {
            query?: {
                status?: string | null;
                search?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                website_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ContentPageList_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_api_v1_websites__website_id__pages__page_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                website_id: string;
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ContentPageDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verification_info_api_v1_websites__website_id__verification_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                website_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_WebsiteVerificationDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_website_api_v1_websites__website_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                website_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebsiteVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_WebsiteVerificationDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_str__str__"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_str__str__"];
                };
            };
        };
    };
}
